name: Larastan

on:
  - pull_request

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
          composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist --working-dir=./docker-laravel/src/tools/larastan

      - name: PHPStan Analyse
        run: ./docker-laravel/src/tools/larastan/vendor/bin/phpstan analyse
